### PR TITLE
ms1428: replace html href value and rename files in a folder

### PR DESCRIPTION
**Pull request by MingtaoSun**
@scoen 
This is the first script for this JIRA
http://ourweb.nla.gov.au/apps/jira/browse/DSCS-1428
It replaces the href attribute value in the area element of the HTML input with the new value specified in the csv file.

### CODE REVIEW

**Comment by MingtaoSun** [comment]
@scoen 
Here is the second script (rename.vbs) for this JIRA http://ourweb.nla.gov.au/apps/jira/browse/DSCS-1428
It renames all the files in a folder to the new file name specified in a csv file

**Comment by shuangzhou** [comment]
nice to see multiculturalism in practice.

**Comment by brycollins** [comment]
what about mac users?

**Comment by MingtaoSun** [comment]
@brycollins , Kavinga has advised only one user with a Windows system is gonna use the script. So at the moment there is no need to write another script for mac users.

**Pull request merged**
